<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "st_address_map"
 *
 * Auto generated by Extension Builder 2014-06-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Address visualization with Google Maps',
	'description' => 'With the extension st_address_map you are able to show addresses out of tt_address in Google Maps. Further it is possible to show the addresses in a list.',
	'category' => 'plugin',
	'author' => 'Thomas Scheibitz',
	'author_email' => 'mail@kreativschmiede-eichsfeld.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'tt_address' => '2.3.4',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);